[package]
name = "smart_file_duplicate_manager"
version = "1.0.0"
edition = "2021"
authors = ["Alexander Suvorov <smartlegionlab>"]
description = "Fast and efficient duplicate file finder written in Rust"
repository = "https://github.com/smartlegionlab/smart-file-duplicate-manager-rs"
license = "BSD-3-Clause"

[dependencies]
blake3 = "1.5"
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17"
rayon = "1.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2.5"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"