[package]
name = "smart_file_duplicate_manager"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Suvorov <smartlegionlab>"]
description = "Smart File Duplicate Manager"
repository = "https://github.com/smartlegionlab/smart_file_duplicate_manager"
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17"
walkdir = "2.5"
